# Generated by Django 5.2.7 on 2025-10-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.BigIntegerField(null=True)),
                ('line_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vcf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('fullpath', models.TextField()),
                ('needs_update', models.BooleanField(blank=True, default=False)),
                ('is_updating', models.BooleanField(blank=True, default=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VcfRow',
            fields=[
                ('row_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_id', models.BigIntegerField(null=True)),
                ('chrom', models.CharField(max_length=150)),
                ('pos', models.PositiveIntegerField()),
                ('id', models.TextField(null=True)),
                ('ref', models.CharField(max_length=150)),
                ('alt', models.TextField(null=True)),
                ('dirty', models.BooleanField(blank=True, default=False)),
                ('vcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcfApi.vcf')),
            ],
            options={
                'ordering': ['line_id'],
            },
        ),
    ]
