# Generated by Django 5.2.7 on 2025-11-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcfApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcfrow',
            name='alt',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='vcfrow',
            name='chrom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vcfrow',
            name='ref',
            field=models.CharField(max_length=100),
        ),
    ]
